### ISSUE TITLE
command use error 

### ISSUE THREAD

**Issue by rungobier** [open-security/vulnpwn#34]
```
vulnpwn > use
use
Traceback (most recent call last):
  File "./vulnpwn", line 19, in <module>
    fw.cmdloop()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/Users/jacksg/data/dev_tools/python_root/vulnpwn/lib/base/base.py", line 116, in do_use
    self.help_load()
AttributeError: Base instance has no attribute 'help_load'
```

**Comment by join-us** [comment]
Thanks @rungobier. Please try it again.
